application: cm-nightlies
version: 7
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /img
  static_dir: img

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /rss
  script: rss.py

- url: /.*
  script: diff.py
